name: Nightly Update Check
on:
  schedule:
    - cron: "0 0 * * *"
  workflow_dispatch:

jobs:

  build:
    runs-on: ubuntu-latest
    steps:

      - uses: actions/checkout@v3

      - name: Log in to registry
        run: echo "${{ secrets.GITHUB_TOKEN }}" | docker login ghcr.io -u $ --password-stdin

      - name: Check if image needs updating
        id: check
        uses: lucacome/docker-image-update-checker@v1
        with:
          base-image: caddy:2-builder
          image: ghcr.io/tylersatre/caddy-namecheap-verification:2

      - name: Build and push image
        uses: docker/build-push-action@v2
        with:
          context: .
          push: true
          tags: ghcr.io/tylersatre/caddy-namecheap-verification:2
        if: steps.check.outputs.needs-updating == 'true'
